---
env: staging
app_port: 8080
server_name: staging.example.com
server_aliases:
  - staging1.example.com
  - staging2.example.com
db_host: staging-db.example.com
app_debug_mode: true
nginx_worker_processes: 1
