---
env: production
app_port: 80
server_name: prod.example.com
server_aliases:
  - www.prod.example.com
  - api.prod.example.com
db_host: prod-db.example.com
app_debug_mode: false
nginx_worker_processes: auto
