---
- name: Deploy database
  hosts: all
  become: yes
  vars_files:
    - ../group_vars/{{ env }}/vault.yml
  roles:
    - role_db
  tags:
    - db

- name: Deploy web server and application
  hosts: all
  become: yes
  vars_files:
    - ../group_vars/{{ env }}/main.yml
    - ../group_vars/{{ env }}/vault.yml
  roles:
    - role_web
    - role_app
  tags:
    - app
