---
- name: Deploy application to staging
  hosts: staging
  become: yes
  vars_files:
    - ../group_vars/staging/main.yml
    - ../group_vars/staging/vault.yml
  roles:
    - role_web
    - role_app

- name: Deploy application to production
  hosts: production
  become: yes
  vars_files:
    - ../group_vars/production/main.yml
    - ../group_vars/production/vault.yml
  roles:
    - role_web
    - role_app
