---
- name: Check inventory and connection
  hosts: all
  gather_facts: no
  tasks:
    - name: Print environment
      debug:
        msg: "Running on {{ inventory_hostname }} in {{ env }} environment"
